//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Web.Http.OData;
using System.ComponentModel.DataAnnotations;
namespace RestaurantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppData
    {
        [Key]
        public int DishId { get; set; }
        public string DishName { get; set; }
        public byte[] DishImage { get; set; }
        public string DishDescription { get; set; }
        public Nullable<int> DishRating { get; set; }
        public Nullable<int> DishPriceRange { get; set; }
        public string DishCuisineType { get; set; }
        public string DishProteinType { get; set; }
        public string DishMeal { get; set; }
        public string RestaurantName { get; set; }
        public string RestaurantDescription { get; set; }
        public string RestaurantStreetAddress { get; set; }
        public string RestaurantCity { get; set; }
        public string RestaurantState { get; set; }
        public string RestaurantZipCode { get; set; }
        public System.Data.Entity.Spatial.DbGeography GPSLocation { get; set; }
        public Nullable<System.TimeSpan> OpenTime { get; set; }
        public Nullable<System.TimeSpan> CloseTime { get; set; }
        public string DishImageUrl { get; set; }
        public string Sparefield1 { get; set; }
        public string Sparefield2 { get; set; }
        public string Sparefield3 { get; set; }
    }
}
